### ISSUE TITLE
GitIgnore isn't working

### ISSUE THREAD

**Issue by bradweiers** [UnityTechnologies/InputSystem_Warriors#2]
I'm getting Library and Temp folders in my project when I clone. Also why isn't the project folder at the root?

**Comment by andytouch** [comment]
This should be fixed now; but let me know if it isn't!

Project folder is not at the root to keep consistency with other projects where other non-Unity project folders such as Concept Art, Raw PSDs, Maya Files, documentation, etc could be included in the repo aswell.

IE:
- Repo Root
--- Unity Project
--- Concept Art
--- Raw PSDs
--- Maya Project
--- Raw Audio Files
--- Documentation and Guides
